name: Glance

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
      arch:
        description: Architecture
        required: true
        type: choice
        options:
          - amd64
          - arm64
          - '386'
          - armv7
        default: amd64

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      GLANCE_TAG: ${{ inputs.tag }}
      GLANCE_ARCH: ${{ inputs.arch }}
    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3

      - name: Install fpm
        run: gem install fpm

      - name: Download Glance tarball
        run: |
          curl -fsSL -o $RUNNER_TEMP/glance.tar.gz \
            "https://github.com/glanceapp/glance/releases/download/$GLANCE_TAG/glance-linux-${GLANCE_ARCH}.tar.gz"

      - name: Extract tarball
        run: |
          tar -C $RUNNER_TEMP -xzf $RUNNER_TEMP/glance.tar.gz
          chmod +x $RUNNER_TEMP/glance

      - name: Download example config
        run: |
          example_config_url="https://raw.githubusercontent.com/glanceapp/glance/refs/tags/$GLANCE_TAG/docs/glance.yml"
          echo -e "# Preconfigured page from ${example_config_url}\n" >> $RUNNER_TEMP/glance.yml
          curl -fsSL $example_config_url >> $RUNNER_TEMP/glance.yml

      - name: Package .deb
        id: package-deb
        run: |
          deb_version=${GLANCE_TAG#v}
          deb_arch=$(sh deb-arch.sh $GLANCE_ARCH)
          deb_package="glance_${deb_version}_${deb_arch}.deb"
          fpm -s dir -t deb -p $deb_package \
            --name glance \
            --version $deb_version \
            --architecture $deb_arch \
            --description "A self-hosted dashboard that puts all your feeds in one place." \
            --url "https://github.com/glanceapp/glance" \
            --maintainer "${GITHUB_ACTOR} <${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com>" \
            --license "AGPL-3.0-or-later" \
            --config-files /etc/default/glance \
            --config-files /etc/glance/glance.yml \
            --deb-systemd glance/glance.service \
              $RUNNER_TEMP/glance=/usr/bin/glance \
              glance/glance.env=/etc/default/glance \
              $RUNNER_TEMP/glance.yml=/etc/glance/glance.yml
          echo "path=$deb_package" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package-deb.outputs.path }}
          path: ${{ steps.package-deb.outputs.path }}

      - name: Upload to Gitea if running in Gitea Actions
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: sh upload-gitea.sh ${{ steps.package-deb.outputs.path }}
